---
title: "Cheng-Lit_Review_Outline"
author: "Yang Cheng"
date: "6/15/2021"
output:
  html_document:

    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    df_print: paged
---
 
# A Multidimensional Approach to Measuring Vulnerability to Poverty of Syrian Refugees in Lebanon
**Journal:** ERF Working Papers Series

**Author**: Angela C. Lyons, Josephine Kass-Hanna and Alejandro Montoya Castano

**Date:** April 2021

**Keywords:** multidimensional poverty, poverty measurement, vulnerability, economic livelihoods, refugees, humanitarian assistance, Middle East and North Africa.

**One or two sentence summary of abstract:** This study constructs a multidimensional livelihood index (MLI) to identify refugee households who are currently poor, and assesses households’ vulnerability to future poverty using a 3-stage Feasible Generalized Least Squares (FGLS) model. **Data: ** This study uses micro-level data from the sixth wave of the Vulnerability Assessment of Syrian Refugees (VASyR)V survey, the only nationally representative household survey collecting observed and self-reported data on various dimensions of the livelihoods of the refugees, including food consumption, health, shelter, education, financial resources, and personal security, among others.

**Keystone references or citations:** The analysis allows us to identify more clearly which households and geographical locations are more vulnerable to experiencing current and prolonged poverty.

**Assumptions:** 


**Statistical methodology: ** 

1. MLI construction


This study build MLI by adopting the framework of MPI to measure the poverty. The MPI  encompasses 3dimensions (education, health, and living standards) and 12 indicators. Each indicator measures a specific deprivation, which makes the MPI easily interpretable and calculable, as it transforms each variable into a binary response. This study adds and modifies some dimensions and indicators to better suit the case of Syrian refugees in Lebanon.

[**How to decompose, interpret, present, key policy messages, key visuals and FAQs of MPI**](https://www.ophi.org.uk/wp-content/uploads/MPI-interpretation-decompositions.pdf)

*Calculation(Table 2):*  To calculate our index, we followed the steps described in Alkire and Santos (2014). 

First, we defined the dimensions, indicators, and the cutoffs to measure deprivation for each indicator (see
Table 2). Our index included 21 indicators that spanned five dimensions: (1) health and food security,
(2) education, (3) living standards, (4), employment, and (5) security and social inclusion. We
assigned weights using two weighting schemes. In our first and primary weighting scheme, we
assigned equal weights to the five dimensions (0.2000 x 5 = 1.000). The weight of each dimension
was then divided equally across the indicators included in each dimension. In the second weighting
scheme, the 21 indicators were given equal weighting (0.0476 x 21 = 1.000). 

Next, we calculated the deprivation score for each household, which ranged from 0 to 1. Households with a deprivation score of 0.33 or higher were classified as multidimensionally poor. Although some estimations of the MPI
have used a different cutoff, the standard in the literature has been 0.33 (e.g., OPHI, 2018). The
percentage of multidimensionally poor households within the sample is known as the headcount ratio
(H). 

In the final step, we calculated our multidimensional livelihood index (MLI) as the product of $H
* A$, where H was the incidence of poverty (the headcount ratio) as defined above, and A was the
average deprivation score, but only for those who were classified as poor (the average intensity of
poverty).  Hence, the MLI score is the proportion of weighted indicators in which multidimensionally poor refugees were deprived, out of all the potential deprivations the whole
refugee population could have experienced.

2. Three-stage FGLS using deprivation scores

P24 in the paper.

**One or two sentence summary of conclusion:** 

**Relevance to our research:** A multidimensional approach can helpus  to more easily identify which dimensions and geographical areas need to be prioritized. Table 2 & Figure 2 & Figure 3 provide some guidelines for us if we are going to apply multidimensional index to measure the labor market vulnerability. 

**Things you did not understand:** Not about this paper, but regarding the construction of multidimensional labor market vulnerability. More specifically, what are the the  dimensions and indicators for our index?

**Value-added (high/medium/low):** medium





# When Labor’s Lost: Health, Family Life, Incarceration, and Education in a Time of Declining Economic Opportunity for Low-Skilled Men (TBC)

**Journal:** The Journal of Economic Perspectives , Vol. 33, No. 2 (Spring 2019), pp. 191-210

**Author**: Courtney C. Coile and Mark G. Duggan

**Date:** Spring 2019

**Keywords:** 

**One or two sentence summary of abstract:** This study seeks to illuminate the broader context in which prime-age men are experiencing economic stagnation. This paper explores changes for prime-age men over time in education, mortality, morbidity, disability program receipt, family structure, and incarceration rates.

**Keystone references or citations:** 

**Assumptions:** 

**Statistical methodology: ** 

Descriptive analysis.

**One or two sentence summary of conclusion:** 

**Relevance to our research:**

**Things you did not understand:** 

**Value-added (high/medium/low):** 

